version: '2'
services:
  server:
    image: 'gocd/gocd-server:v17.11.0'
    ports:
      - 8153:8153
      - 8154:8154
    volumes:
      - '${PWD}/plugins/external:/godata/plugins/external'
      - '${PWD}/config:/godata/config/'
  agent:
    image: 'gocd/gocd-agent-debian-8:v17.11.0'
    environment:
      GO_SERVER_URL: 'https://server:8154/go'
